base_url = "https://cryosnake22.github.io/charlopl.com"
title = "CharloPL"
description = "My personnal website"
build_search_index = false
feed_filenames = ["rss.xml"]
generate_feeds = true
compile_sass = true
minify_html = true
theme = "redux"

[markdown]
highlight_code = true
render_emoji = true
smart_punctuation = true
highlight_theme = "ayu-dark"
external_links_no_referrer = true
bottom_footnotes = true

[extra]
toc = true
use_cdn = false
favicon = "/icon/favicon.png"
favicon_extra = false
theme = "toggle"                                                       # light, dark, auto, toggle
comment = false
fancy_code = true
dynamic_note = true
repo_url = "https://github.com/CryoSnake22/charlopl.com/tree/gh-pages"
mathjax = true
mathjax_extra = true

menu = [
  { name = "/posts", url = "/posts", weight = 1 },
  { name = "/projects", url = "/projects", weight = 2 },
  { name = "/about", url = "/about", weight = 3 },
]

socials = [
  { name = "github", url = "https://github.com/CryoSnake22", icon = "github" },
  { name = "youtube", url = "", icon = "youtube" },
  { name = "rss", url = "", icon = "rss" },
  { name = "linkedin", url = "", icon = "linkedin" },
]

custom_css = []

[extra.analytics]
enabled = false

# [extra.analytics.goatcounter]
# user = "your_user"
# host = "example.com" # default= goatcounter.com

# [extra.analytics.umami]
# website_id = "43929cd1-1e83...."
# host_url = "https://stats.mywebsite.com" # default: https://analytics.eu.umami.is
# keep for now
